var data = [
    {
        caption: "Fomites",
        question:"In the Movie Contagion, Dr Mears mentions the potential for MEV-1 to be transmitted via fomites which refers to transmission from surfaces. The movie also emphasises on fomites by highlighting infected individual touching various surfaces around them.",
        follow:"Is the movie's depiction of disease transmission accurate?",
        meme: require("./Images/fomite.jpg"),
        answer: "True",
        discussion:"A highlight about the movie is its accurate portrayal of how diseases are transmitted between hosts. In epidemiology, a fomite is any inanimate object that, when contaminated with infectious agents, act as a vehicle for disease transmission [1]. Fomites become contaminated with viruses by direct contact with body secretion or fluids or contact with an airborne virus [2]. Once contaminated, the transfer of an infectious virus occurs through contact between a fomite and an animate object [2]."
    },
    {
        caption: "MEV-1",
        question:"In the movie, MEV-1 is a deadly disease that originated from a bat and then a pig.",
        follow:"Is 'MEV-1' a real virus?",
        meme: require("./Images/nipah.png"),
        answer: "False",
        discussion:"Thankfully, the MEV-1 virus is fictional. Otherwise, the world would be in a state of emergency. However, the MEV-1 virus was inspired by real viruses such as the Nipah virus. The Nipah virus is a zoonotic virus known to be transmitted from infected pigs via pig tissue and infected fruit bats via saliva and urine on fruit and fruit produce [3]. These as some very obvious parallels that can be drawn between MEV-1 and the Nipah virus."
    },
    {
        caption: "R-Naught",
        question:"In the movie Contagion, the scientists used the R-naught number to predict the spread of the disease.",
        follow:"Is this an accurate use of the R-naught number?",
        meme: require("./Images/R0.gif"),
        answer: "True",
        discussion:"The R-naught, in epidemiology, is the basic reproduction number. It refers to the basic reproduction rate of an infection; the number of new cases generated by one case [4].  The r-naught is affected by several factors; the rate of contacts in the host populations, the probability of infection transmission during contact and the duration of the infectiousness [5].  it is used to estimate the spread in a susceptible population. For example, the R-naught of ebola is 2 and the R-naught of HIV is 4 [5]."
        
    },
    {
        caption: "Epidemiology",
        question:"In the movie 'Contagion',  Dr. Leonora Orantes, a WHO epidemiologist, was sent to Hong Kong to trace the source of the MEV-1 virus.",
        follow:"Is this an accurate depiction of what an epidemiologist would do?",
        meme: require("./Images/epidemilogist.gif"),
        answer: "True",
        discussion:"In the world of public health, epidemiologists study diseases within populations of people. These scientists analyse the cause of a disease outbreak in order to treat the disease and prevent future outbreaks [6]. Outbreak investigation, observational studies and risk identification allow for the implementation of disease control measures [7] such as quarantine and treatment [8]."
        
    },
    {
        caption: "Vaccine",
        question:"In the movie 'Contagion', a vaccine was discovered by Dr. Hextall and mass produced within months of the first outbreak of 'MEV-1'.",
        follow:"Is this speed of vaccine development feasible in the modern day (2019)?",
        meme: require("./Images/vaccine.gif"),
        answer: "False",
        discussion:"For the development of the vaccine for MEV-1, it appears that the film took the Hollywood approach and took the route of convenience. In the real world, vaccines usually take between 10 to 15 years to develop. This is because vaccines go through many phases of development including research, discovery, pre-clinical testing and clinical testing before regulatory approval with the approval process taking another lengthy two years. Once approved, the vaccine is then manufactured and shipped to where it is needed [9]."
        
    },
    {
        caption: "Zoonotic Diseases",
        question:"In the movie 'Outbreak', Betsy the capuchin monkey was the host that brought the Motaba virus into America from the nation of Zaire.",
        follow:"Is this feasible in the real world?",
        meme: require("./Images/zoonotic.png"),
        answer: "False",
        discussion:"This was indeed a trick question. Capuchin monkeys are native to South America [10]. Hence, it would be very unlikely for a capuchin monkey to be infected and act as transport for a disease originating in central Africa. The Motaba virus, though fictional, is an excellent example of a zoonotic disease. Zoonotic diseases are diseases spread between animals and humans. Diseases like Ebola and salmonellosis are examples of non-fictional zoonotic diseases [20]."
    },
    {
        caption: "Motaba Virus",
        question:"In the movie, Outbreak, the Motaba virus is a haemorrhagic virus which has a 100% mortality rate.",
        follow:"Is the Motaba virus a real virus?",
        meme: require("./Images/ebola.jpg"),
        answer: "False",
        discussion:"Thankfully, like MEV-1, the Motaba virus is fictional. However, the Motaba virus is based on the ebola virus which is also a haemorrhagic virus [13]. Even the microscope image of the Motaba virus in the film is actually just the ebola virus.  However, the ebola virus only has a mortality of approximately 50% [13].  Interestingly, around the time of the movie's release in 1995, Zaire was experiencing an ebola outbreak [14]."
    },
    {
        caption: "Anti-serum",
        question:"In the movie Outbreak, the cure was created for the whole town by using the anti-bodies of the host monkey to generate an Anti-serum.",
        follow:"Is this possible in modern day medicine?",
        meme: require("./Images/antiserum.jpg"),
        answer: "False",
        discussion:"Anti-serum is blood serum containing antibodies that is used to spread passive immunity [15]. A common use case for anti-serum is the treatment of envenomation in humans. Anti-serum is currently used to treat Ebola with a low success rate [16]. The production of some anti-serum is produced by animals such as horses[15]. Anti-serum production requires blood withdrawal [17]. Hence, it is impossible for a small monkey to produce enough anti-serum for an entire town of people in a single day."
    },
    {
        caption: "Mutations", 
        question:"In the movie Outbreak, the original strain of the Motaba virus mutates and becomes airborne. It is later found that the virus had developed spikes on the exterior.",
        follow:"Is this mutation possible in viruses?",
        meme: require("./Images/mutate.gif"),
        answer: "True",
        discussion:"Viral evolution occurs constantly and it is how mutations occur in influenza viruses and human immunodeficiency viruses occur. Influenza and HIV are RNA viruses. RNA viruses are encoded in RNA. Unlike DNA viruses, RNA viruses do not have a 'proofreading' step in its replication and will often have mistakes and thus will mutate very frequently [18]. This gives RNA viruses evolutionary advantages meaning it is possible for viruses to mutate into a strain that can remain suspended in the air (I.e. airborne) [19]."
        
    }
]

export default data